Fix serialization of undefined values
Return undefined values as nil atom instead of crashing entire serialization call. Otherwise you get error like this:
```
OutputException: unknown javascript type
    at new OutputException (d:\Projects\Research\Relay\_build\dev\lib\relay\priv\node\node_modules\@beenotung\erlang_js\Erlang.js:101:17)
    at Object._term_to_binary (d:\Projects\Research\Relay\_build\dev\lib\relay\priv\node\node_modules\@beenotung\erlang_js\Erlang.js:895:19)
    at Object._object_to_binary (d:\Projects\Research\Relay\_build\dev\lib\relay\priv\node\node_modules\@beenotung\erlang_js\Erlang.js:960:33)
    at Object._term_to_binary (d:\Projects\Research\Relay\_build\dev\lib\relay\priv\node\node_modules\@beenotung\erlang_js\Erlang.js:885:39)
    at Object._object_to_binary (d:\Projects\Research\Relay\_build\dev\lib\relay\priv\node\node_modules\@beenotung\erlang_js\Erlang.js:960:33)
    at Object._term_to_binary (d:\Projects\Research\Relay\_build\dev\lib\relay\priv\node\node_modules\@beenotung\erlang_js\Erlang.js:885:39)
    at Object.term_to_binary (d:\Projects\Research\Relay\_build\dev\lib\relay\priv\node\node_modules\@beenotung\erlang_js\Erlang.js:481:40)
```